### ISSUE TITLE
preferred or advised procedure for letsencrypt certificate renewal

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-installer#116]
Hi, 

I've used the modoboa installer and would like to know what the advised or preferred way of renewing the letsencrypt certificate would be. 

Reason I am asking is that the cron script that deals with this fails because port 443 is occupied by the nginx server. Manually stopping it and then running certbot-auto works. I guess best would be to let the cron script also handle stopping the nginx service. 

Cheers!

**Comment by almereyda** [comment]
This should be handled by https://github.com/modoboa/modoboa-installer/blob/2f61272bf8d62ddd9a7c6ca071c3b58d303ac020/modoboa_installer/ssl.py#L83-L84 already.

Yet my certificates just ran out and it appears this cronjob did not run. Attempting the major version upgrade from 1.6.2 to 1.7.2 and can report back in three months if it helped.

**Comment by tonioo** [comment]
A cron job is already installed but I don't have much feedback about it. @almereyda Do you have more information about why it failed?

**Comment by JayBeRayBearGun** [comment]
The problem is that for the cron script to work and update the certificate the certbot-auto needs to have access to port 443 which is occupied by the webserver process. So, this needs to be stopped first before the cron script can function.  I did it by hand,.. but should be amended in the script naturally

**Comment by almereyda** [comment]
The lines of `ssl.py` I had linked above should take care of stopping and reloading nginx. Yet since this is not proven to not work completely, there is also [`certbot-auto`'s standalone mode](https://certbot.eff.org/docs/using.html#standalone) which can be used with a similar configuration to [what is linked](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/nginx_location.conf) in https://github.com/modoboa/modoboa-installer/issues/39#issuecomment-271004120. It would need to be included as an `include` directive in https://github.com/modoboa/modoboa-installer/blob/2f61272bf8d62ddd9a7c6ca071c3b58d303ac020/modoboa_installer/scripts/files/nginx/nginx.conf.tpl#L11 if Let's Encrypt is set as certificate type in `installer.cfg`.

Unfortunately I don't have more concrete debug information available to why the cronjob failed.

**Comment by tonioo** [comment]
@JayBeRayBearGun @almereyda I'll try to make more tests about this.

**Comment by almereyda** [comment]
The Let's Encrypt `cron` still regularily fails (did three months pass since my last visit in this issue?) due to a missing new line character at the end of the line produced by https://github.com/modoboa/modoboa-installer/blob/2f61272bf8d62ddd9a7c6ca071c3b58d303ac020/modoboa_installer/ssl.py#L81-L86

I have added this manually now to the file and will report back in three months if it works.

References can be:

* https://github.com/ansible/ansible-modules-core/pull/4330/files
* http://www.brandonrubin.me/2013/08/19/i-forgot-my-newline/
* https://www.vnhelp.co.uk/hs/ws/config/crontabs/

**Comment by JayBeRayBearGun** [comment]
To be sure I manually execute the commandline from the crontab (after suspend the web server).

**Comment by almereyda** [comment]
@JayBeRayBearGun I also did it manually, but have also appended the missing newline character, to see if it runs. We may want to provide a PR to `ssl.py`, to make sure other users don't run into the same issue again.
