### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by csergiu** [modoboa/modoboa-installer#157]
I want to uninstall Modoboa (alongside with Postifix/Dovecot) on an Ubuntu 14.04 server. How can I accomplish this? Thanks.

**Comment by tonioo** [comment]
The installer does not provide any uninstall feature. You'll have to do it manually using ``apt`` (postfix, dovecot, amavisd-new, nginx, uwsgi, etc.) You can take a look a the files located under ``modoboa_installer/scripts/`` to know which packages are installed.

**Comment by akilawickey** [comment]
Better to provide some way to remove this also.

**Comment by RailRunner16** [comment]
yeah, it makes no sense not to have an installer when the service errors after a clean installation on almost every platform it's installed on 😠

**Comment by UOCecalero** [comment]
+1

**Comment by mjhd** [comment]
This actually made me so mad, you should really warn people, especially given that the software is full of holes and people will likely want to uninstall 😠😠

**Comment by mjhd** [comment]
THIS MAKES ME SOOOOO MAD!!! 😠😠

**Comment by dudeisbrendan03** [comment]
This aint that great

**Comment by aliqandil** [comment]
Well I've tried this installer about a year ago and it just asked for a bunch of passwords and rather intrusively messed with my nginx setup. so as I'm trying to uninstall it by following the installation manual, I'll condense what I'll see and what I did here so I might help someone else:

1- First it creates a user, called modoboa, so:
`sudo userdel -r modoboa`
It told me a process (PID 1979) was using it, so I just killed it. (you may want to be more kind)
`sudo kill -9 1979` **Carefull, don't just copy this**
I remember it's home folder was "/srv/modoboa" and when I check it doesn't exist. Good so far.

2- It installed mysql, I don't need it since i use postgres, so I just [remove it](https://linuxscriptshub.com/uninstall-completely-remove-mysql-ubuntu-16-04/)!

3- a cron job was created, so:
`sudo rm /etc/cron.d/modoboa`

4- now we'll get to the WebServer part, I didn't have apache setup, and nothing was created in my apache config files. (`ls /etc/apache2/sites-available`)
but there were some config files created in my nginx folder (`ls /etc/nginx/sites-available`):
`rm autoconfig.MYDOMAIN.com.conf mail.MYDOMAIN.com.conf`

5- Rather aggressivley remove other componenst and their config file. read first then use!
`sudo apt remove dovecot-core && sudo rm -rf /etc/dovecot`
`sudo apt remove postfix && sudo rm -rf /etc/postfix` (I might install a clean version later)
`sudo apt remove uwsgi && sudo rm -rf /etc/uwsgi` (since I use gunicorn in python env, I don't need it)
`sudo apt remove autoconf razor spamassassin opendkim`

I'm hoping I didn't miss anything.

**Comment by endelwar** [comment]
Thank you @aliqandil!
I had to remove more pieces using version 1.16.
- Postgres was installed, and I'm using MySql: `apt-get --purge remove postgresql postgresql-11 postgresql-client-11 postgresql-client-common postgresql-common`
- Remove supervisor config for radical and policy: `rm /etc/supervisor/conf.d/policyd.conf /etc/supervisor/conf.d/radicale.conf && service supervisor restart`
- after deleting user modoboa, a group with the same name was not removed because www-data was a member of it: `gpasswd -d www-data modoboa && groupdel modoboa`
- remove users radical and automx: `userdel -r radicale && userdel -r automx`

**Comment by grantiago** [comment]
What a mess. 
Thanks @aliqandil! && @endelwar  :beer: 
Even after following all the steps. My boot log was filled with: 
`Aug 18 13:28:39 xxx install: invalid user modoboa`
`Aug 18 13:28:39 xxx uwsgi[904]:    ...fail!`
`Aug 18 13:28:39 xxx systemd[1]: uwsgi.service: Control process exited`

 on Ubuntu 18.04.5 LTS I had to do the following: 
`update-rc.d -f uwsgi disable`
 `update-rc.d -f uwsgi remove`
 `systemctl disable uwsgi`
3 hours later  I'm praying everything 🐍  continues to run.

**Comment by appzer0** [comment]
Hi, 

On a pure dedicated-to-mail-only server, I had to:

```
apt purge mysql* postgresql*
apt purge nginx
apt purge razor spamassassin postfix* dovecot* clamav*
apt purge redis*
apt purge uwsgi
apt purge supervisor*
rm -rf /etc/razor/
rm -rf /etc/dovecot/
rm -rf /var/lib/dovecot/
rm -rf /var/lib/amavis/
rm -rf /var/lib/nginx/
rm -rf /var/lib/redis/
rm -f /etc/supervisor/conf.d/policyd.conf /etc/supervisor/conf.d/radicale.conf
rm -rf /var/log/uwsgi/
rm -rf /etc/uwsgi/
rm -rf /srv/automx
rm -rf /srv/vmail/
rm -rf /srv/radicale/
rm -f /etc/cron.d/amavisd-new 
rm -f /etc/cron.d/modoboa 
rm -f /etc/cron.d/letsencrypt 
rm -f /etc/cron.d/postwhite 
rm -f /etc/cron.daily/spamassassin
rm -rf /usr/local/bin/postwhite
rm -rf /usr/local/bin/spf-tools
rm -rf /usr/local/bin/postlogin.sh

```
