### ISSUE TITLE
add configuration option to choose installed/enabled protocols, e.g. imap, pop3 etc.

### ISSUE THREAD

**Issue by christoph-mueller-crixp** [modoboa/modoboa-installer#17]
currently, the modoboa-installer does NOT install/enable pop3 support; while it is easy to fix this omission after the installation has completed, it would be nice if one could configure which protocols to install/enable, e.g. in the file installer.cfg

as a workaround, I added pop3 (and pop3s) support as follows on Ubuntu 14.04.3 LTS:

> sudo apt-get install dovecot-pop3d
> sudo echo protocols = \$protocols pop3 > /usr/share/dovecot/protocols.d/popd.protocol

**Comment by hadifarnoud** [comment]
can anyone confirm this is working? just these two lines will enable POP3 with authentication?

**Comment by jeremyevans6** [comment]
The above lines broke my installation and prevented webmail from working. Webmail could no longer connect with IMAP since the protocol line was replaced with exclusively the POP3 protocol. (I did not have a $protocols variable set.)

The trick is adding all of the desired protocols into the dovecot config:
>protocols = imap imaps lmtp sieve pop3 pop3s
