### ISSUE TITLE
Warning: Trivial rewrite

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#183]
# Impacted versions

* Distribution: Debian
* Codename: Jessie
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce

- Install Modoboa 1.10 with the installer

# Current behaviour

Watch those lines to appear in the `mail.log`

```
Feb 21 22:49:02 email postfix/trivial-rewrite[17063]: warning: do not list domain email.ecobytes.net in BOTH mydestination and virtual_mailbox_domains
```

Please note after upgrading #39 the system was trying to send maintenance messages to `vmail@email.ecobytes.net`, which did not exist, why we created it as an alias to `postmaster@email.ecobytes.net`.

# Expected behavior

The error does not appear.

**Comment by tonioo** [comment]
Actually, it is not an installer issue. This change was introduced here (https://github.com/modoboa/modoboa-installer/commit/111cb83b07270032a928425009522d94b0c82b88) because of complaints about system messages not being delivered to root/vmail mailbox. With a fresh install, modoboa does not declare any domain so you won't see this error.

In your case, email.ecobytes.net is listed in mydestination and you have declared an email.ecobytes.net domain in modoboa. You just have to decide which one you want to keep. I'd say you can empty the mydestination parameter.
