### ISSUE TITLE
[Feature Request] Virtual Domain SSL Cert

### ISSUE THREAD

**Issue by kryskool** [modoboa/modoboa-installer#199]
_From @jaketame on July 10, 2017 6:47_

# Impacted versions

* Modoboa: All
* installer used: Yes
* Webserver: Nginx

# Current behavior
- Currently only top level domain certificate is generated, will cause issues with domains that want to hide the orginal mail server name, such as mail.primary.uk, mail.client1.uk

# Expected behavior
 - On domain creation within gui, option to enable SSL for the domain, automatic letsencrypt certificate generation (Multi-Domain SAN) and restart of services.

# Potential Implementation 
https://github.com/mail-in-a-box/free_tls_certificates

_Copied from original issue: modoboa/modoboa#1181_

**Comment by kryskool** [comment]
_From @jaketame on July 11, 2017 6:49_

IDEA:

Possibility to use the free_tls_certificates as a python plugin, store the ssl domains in db table

1) Admin interface to create/update with option to enable SSL for domain such as mail.new.com
2) Update domains sql table
3) Trigger issue.certificate via driver.py plugin, will detect new domain from db table and issue new cert, first domain will be primary domain on cert with others as additional domains (SAN)
4) Restart mail services.

HTTP access for .acme-challenege only everything else redirected to HTTPS.

Thoughts?

**Comment by CyberfoxDK** [comment]
Deffently a thing that would be nice.
Actually needing it for my deployments...

**Comment by PsyDafke** [comment]
I would also like to vote 'me too' on this one.
It would be nice if hosting multiple domains, that one could use the individual domain names for mx/webmail/... Now only the hostname has a valid LE cert, and none of the accepted domains.
I understand one could use the hostname for everything, but that doesn't look as clean.
@tonioo : Any plans/update on this? I'm willing to sponsor a part of such feature (like I did on the updater)

**Comment by tonioo** [comment]
@PsyDafke I'm not sure to understand the need. You'd like the certificate to be valid for different domain names (ie. the ones that might be used for mail, webmail, imap, smtp, whatever)? You're not talking about a different certificate for each hosted mail domain, right?
If your answer is the first choice then I guess a wildcard certificate should do the trick?

**Comment by PsyDafke** [comment]
@tonioo I'm aware of a wildcard possibility, but this is not the case.
When hosting several independent domains (for mail, webmail, ...), we would like to have mail.hosted-domain.tld and webmail.hosted-domain.tld have their own LE certs.
That way, you don't have to use 1 domain for all users to connect to, and they all can use their own (which looks more professional)

**Comment by tonioo** [comment]
@PsyDafke Ok I see, but it would only work for web interfaces because nginx does support virtual hosts. SMTP/IMAP servers only accept one certificate.

**Comment by CyberfoxDK** [comment]
If possible this would deffently improve the product.


Sendt fra min Samsung Galaxy-smartphone.-------- Oprindelig besked --------Fra: PsyDafke <notifications@github.com> Dato: 25/02/2019  11.25  (GMT+01:00) Til: modoboa/modoboa-installer <modoboa-installer@noreply.github.com> Cc: CyberfoxDK <hfsvendsen@mail.dk>, Comment <comment@noreply.github.com> Emne: Re: [modoboa/modoboa-installer] [Feature Request] Virtual Domain
  SSL Cert (#199) 
@tonioo I'm aware of a wildcard possibility, but this is not the case.

When hosting several independent domains (for mail, webmail, ...), we would like to have mail.hosted-domain.tld and webmail.hosted-domain.tld have their own LE certs.

That way, you don't have to use 1 domain for all users to connect to, and they all can use their own (which looks more professional)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/modoboa/modoboa-installer","title":"modoboa/modoboa-installer","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/modoboa/modoboa-installer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PsyDafke in #199: @tonioo I'm aware of a wildcard possibility, but this is not the case.\r\nWhen hosting several independent domains (for mail, webmail, ...), we would like to have mail.hosted-domain.tld and webmail.hosted-domain.tld have their own LE certs.\r\nThat way, you don't have to use 1 domain for all users to connect to, and they all can use their own (which looks more professional)"}],"action":{"name":"View Issue","url":"https://github.com/modoboa/modoboa-installer/issues/199#issuecomment-466957784"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/modoboa/modoboa-installer/issues/199#issuecomment-466957784",
"url": "https://github.com/modoboa/modoboa-installer/issues/199#issuecomment-466957784",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by thejhh** [comment]
Doesn't this mean, that autoconfig / autodiscrovery doesn't work over SSL either on secondary email domains?

The autoconfig started to work in Thunderbird only after I created a proxy in nginx to the primary address, and created SSL certificate manually.

**Comment by tonioo** [comment]
@thejhh Autoconfig / autodiscover use HTTP requests to work so there is no problem here, you just need to configure your HTTP server correctly (as you did).
What won't work is SMTP/IMAP connections.

**Comment by thejhh** [comment]
I am currently using Modoboa installation and the Nginx setup which came with it.

I had to make a custom script on the Modoboa server which will use Let's Encrypt to issue certificates for all customer domains and setup Nginx configuration for those domains.

So now, when somebody adds a domain on the Modoboa admin / reseller interface, I have to run this script also to make autoconfig/autodiscover work properly. 

*I think Modoboa should generate those certificates and manage Nginx automatically.*

**Comment by thejhh** [comment]
Also, it doesn't seem to use HTTP but HTTPS on Thunderbird, since I had working setup for HTTP -- but not *HTTPS*.
