### ISSUE TITLE
Internal Server Error after fresh install

### ISSUE THREAD

**Issue by MateusFRz** [modoboa/modoboa-installer#229]
# Impacted versions

* Distribution: Debian
* Codename: Jessie
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce
> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py phonix-company.fr

# Full trace using --debug option or current behaviour

> 2018/08/04 21:56:13 [crit] 545#545: *1 connect() to unix:/run/uwsgi/app/modoboa_instance/socket failed (2: No such file or directory) while connecting to upstream, client: 81.65.117.88, server: mail.phonix-company.fr, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.phonix-company.fr"
2018/08/04 21:56:13 [crit] 545#545: *1 connect() to unix:/run/uwsgi/app/modoboa_instance/socket failed (2: No such file or directory) while connecting to upstream, client: 81.65.117.88, server: mail.phonix-company.fr, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.phonix-company.fr", referrer: "https://mail.phonix-company.fr/"

# Question
The current mail server is installed on https://mail.phonix-company.fr
and show "Internal Server Error".

**Comment by ictinc** [comment]
I'm currently facing the same issue. I'm using Debian 9.5 and did a fresh install and was welcome with an internal error. 
After reboot I was shown a login screen in which I logged on with the default username/password. Unfortunately this led to the same error appearing.

**Comment by tonioo** [comment]
@ictinc Set DEBUG to True inside the settings.py file and reload uwsgi, you will see more info.

**Comment by ictinc** [comment]
As the Ingram wasn't working I destroyed the droplet. Today, however, when I try to install the install fails everytime with the following error:

Traceback (most recent call last):
  File "./run.py", line 111, in <module>
    main(sys.argv[1:])
  File "./run.py", line 99, in main
    scripts.install("nginx", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 149, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 64, in post_run
    self._setup_config("automx", hostname)
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 42, in _setup_config
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 141, in copy_from_template
    with open(dest, "w") as fp:
IOError: [Errno 2] No such file or directory: '/etc/nginx/sites-available/autoconfig.mastersinweb.hosting.conf'

Also APT stops working which, I think explains the above error. 

When trying to run APT I'm faced with the following error:
FATAL > failed to fork

I tried installing in Debian 9.5 2 times ending in the and error and once in Ubuntu 18.04 also resulting in the same error. The same with apt.

I finally decided to upgrade the memory of my droplet to 2Gb instead of 1Gb which has solved all issues. 

So for anyone facing this issue, don't be cheap (like me) and just use the minimum recommended 2Gb RAM. It will save you a lot of time. :)
