### ISSUE TITLE
The installer kills all processes on the machine

### ISSUE THREAD

**Issue by RailRunner16** [modoboa/modoboa-installer#250]
# Impacted versions

* Distribution: Ubuntu
* Codename: Xenial
* Arch: 32
* Database: Doesn't fucking matter

# Steps to reproduce
Just run the installer 😠 
# Full trace using --debug option or current behaviour
no trace

# Expected behavior
expect all processes on the system to be immediately killed, save NGINX
everything that stopped:
- RethinkDB (you idiots owe me big time, because my database lost all of its data, and i'm still recovering from the loss)
- PM2 (every pm2 app was deleted by the way)

# Video/Screenshot link (optional)

**Comment by Toniob** [comment]
Hi,

Thanks a lot for you kind words. It is always a pleasure to get nice messages like this one. It fills our hearts with a lot of love.

About your issue. The modoboa installer doesn't kill other processes. If you check carefully, it was probably an Out of Memory which triggered the oom killer. Maybe you didn't realize that Modoboa, and all its stack, do need memory. What a surprise !

If your processes do not support a kill signal, maybe you're not using what's good for your data, or maybe you've configured them badly. Because it can happen, you should be ready for it. And I'm pretty sure that those data are not important, because nobody would install a new stack on a production server, without testing it before, right ?

Good luck and have a nice day !

**Comment by RailRunner16** [comment]
umm, half of my storage is devoted to swap memory, i think my memory is fine. and yes i could have worded my issue a bit nicer, sorry about that. i fixed everything up, and turns out, i was able to recover my data. I can understand that modoboa would take a lot of memory, but not that much. Maybe try cutting back the memory usage a bit??
