### ISSUE TITLE
managesieve and webmail fail with non email usernames

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#42]
Either [`modoboa-sievelib` is needed](https://github.com/modoboa/modoboa-installer/issues/41) not to let `/sfilters/` show

> Error: Connection to MANAGESIEVE server failed, check your configuration

or another part fails silently.

**Comment by tonioo** [comment]
Which user are connected with ?

**Comment by tonioo** [comment]
Ok, I guess to tried with the admin user (like https://github.com/modoboa/modoboa-webmail/issues/36).
If I understand correctly, you defined an email address for the default admin user (Mail tab) without modifying the username in the same time, right ?
If that's true, your are in a scenario that can't work with the webmail or the sieve editor because modoboa will try to open connections (IMAP or MANAGESIEVE) using "admin" as username whereas dovecot only expects email addresses...
I think the only way to make this work would be to force equality between username and email address when this last one is defined.

**Comment by almereyda** [comment]
@kryskool @tonioo As much as I respect your maintenance decisions on this issue, it has been rambling in my head for quite a while. There was an argument one day, that a default `admin` username invites for brute force attacks.

Additionally, why not provide a default `admin@modoboa.domain.tld` username instead, already having `postmaster`, `hostmaster` and `abuse` aliases defined. This could even ease deployment a bit and this error "disappears" by itself.

**Comment by tonioo** [comment]
@almereyda Are you talking about a default domain that would be created by the installer with an admin and default aliases ?

**Comment by almereyda** [comment]
Yes, I suggest to use the instances FQDN for maintenance reasons,
simplyfing access patterns.

**Comment by tonioo** [comment]
Ok, so this is definitely an installer feature since we don't have any
fqdn when Modoboa is deployed manually...

**Comment by almereyda** [comment]
[`instance.cfg`](https://github.com/modoboa/modoboa-installer/blob/master/installer.cfg#L63) also reads

    postmaster_address = postmaster@localhost

which seems an implicit vote for such standard patterns.

**Comment by tonioo** [comment]
Would you add this value to the installer.cfg file ?
