### ISSUE TITLE
NOQUEUE: reject: RCPT from [x.x.x.x]:39437: 450 4.3.2 Service currently unavailable;

### ISSUE THREAD

**Issue by DenJohX** [modoboa/modoboa-installer#56]
Using the default installation of modoboa, I'm having constant log messages saying there is no queue left when receiving a email, Here is the log for an incoming email from gmail (y.y.y.y) to myhost (x.x.x.x): 

```
Jul 13 13:25:15 myhost postfix/postscreen[21780]: CONNECT from [y.y.y.y]:32801 to [x.x.x.x]:25
Jul 13 13:25:15 myhost postfix/dnsblog[21784]: addr y.y.y.y listed by domain dnsbl.sorbs.net as 127.0.0.6
Jul 13 13:25:21 myhost postfix/tlsproxy[21789]: CONNECT from [y.y.y.y]:32801
Jul 13 13:25:21 myhost postfix/tlsproxy[21789]: Anonymous TLS connection established from [y.y.y.y]:32801: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jul 13 13:25:21 myhost postfix/postscreen[21780]: NOQUEUE: reject: RCPT from [y.y.y.y]:32801: 450 4.3.2 Service currently unavailable; from=<someone@gmail.com>, to=<someone@myhost.com>, proto=ESMTP, helo=<mail-io0-f178.google.com>
Jul 13 13:25:21 myhost postfix/postscreen[21780]: HANGUP after 0.24 from [y.y.y.y]:32801 in tests after SMTP handshake
Jul 13 13:25:21 myhost postfix/postscreen[21780]: PASS NEW [y.y.y.y]:32801
Jul 13 13:25:21 myhost postfix/tlsproxy[21789]: DISCONNECT [y.y.y.y]:32801
Jul 13 13:25:21 myhost postfix/postscreen[21780]: DISCONNECT [y.y.y.y]:32801
```

But the load is very low, about a dozen emails a day per user, with just 5 users. This problem causes huge delays. Sometimes the emails arrives up to 2 - 3 hours late.

What could be causing this delays? The log doesnt show any other errors.

**Comment by tonioo** [comment]
This  "delay" is introduced by postscreen (which is enabled by default). It's a protection mechanism similar to greylisting.
http://www.postfix.org/POSTSCREEN_README.html

**Comment by DenJohX** [comment]
I ended up disabling postscreen, for a high load mail server maybe its not a big deal but for a small one the delays can cause much trouble, you surely not want to wait up to 2 hours for an important email.

This happens mainly with gmail and other big services wich doesnot try to resend the email via the same ip.

Thanks for the help!.

**Comment by dhaupin** [comment]
@DenJohX Postscreen is a useful feature when the right ip's are whitelisted. However, by default, too many are blacklisted. What I did to "solve" this issue was to leave postscreen on and comment out `dnsbl.sorbs.net` within the `/etc/postfix/main.cf`. Magically the mail providers such as Gmail began working again without [significant/any] delay.

Although postscreen is cool, `dnsbl.sorbs.net` seems way too monolithic and blocks Gmail ips. Apparently Google and Sorbs have been back and forth bickering for years to no resolve. Yes Gmail is home to large amounts of spam, but it's also home to massive amounts of legit users/mail. In my case, like yours, there are only 5 domains and I was able to run a tiny modoboa srv on a $5 768mb Vultr instance (~350mb used) by using Gmail as the webmail+antivirus and disabling clamav. Nothing nefarious about that, but sorbs thinks otherwise. Postscreen still blocks tons of other attempts using the other 4 major blacklists (or any others you add).

Also, there is this cron util: https://github.com/stevejenkins/postwhite which will find Gmail and other ranges based on SPF records and apply them to the postscreen whitelist. I haven't had a need to use that yet, but it's an option if you want both postscreen and sorbs enabled. Hope that clarifies.

**Comment by msssltd** [comment]
After a number of hours testing a fairly clean install of modoboa on Debian 8 (Jessie), using the installer, the only way I could get postfix to accept mail from hotmail was by disabling almost all the 'deep inspection' tests.  Presumably this applies to the other multi-ip services, like gmail.

Testing was not as methodical as I would like, so if someone can improve, please do.

`
#msssltd 210617 postscreen deep inspection

postscreen_greet_banner = Welcome, please wait... 
postscreen_greet_action = enforce

#hotmail is rejected
#when bare_newline test is enabled 
#with action: ignore, enforce or drop
#postscreen_bare_newline_enable = yes
#postscreen_bare_newline_action = enforce

#hotmail is rejected, when pipeline test is enabled, with action: ignore, enforce or drop
#postscreen_pipelining_enable = yes
#postscreen_pipelining_action = enforce

#hotmail is rejected, when non_smtp test is enabled, with action: ignore, enforce or drop
#postscreen_non_smtp_command_enable = yes
#postscreen_non_smtp_command_action = enforce
'

**Comment by blackyzero** [comment]
seems, i am getting same issue and this is still not being solved in current release 1.9.1
anyone has idea to fix it. Thanks alot.

**Comment by belzebub40k** [comment]
I had the same problem and was confused as I expected postscreen to hand over the connection to postfix after all tests succeeded. After reading the postfix man page it turned out everything is working as intended. Yust leaving this here in case anybody else runs into the same problem.

_http://www.postfix.org/POSTSCREEN_README.html#victory_
> When any "deep protocol tests" are configured, postscreen(8) cannot hand off the "live" connection to a Postfix SMTP server process in the middle of the session. Instead, postscreen(8) defers mail delivery attempts with a 4XX status, logs the helo/sender/recipient information, and waits for the client to disconnect. The next time the client connects it will be allowed to talk to a Postfix SMTP server process to deliver its mail. postscreen(8) mitigates the impact of this limitation by giving deep protocol tests a long expiration time.

**Comment by demanl** [comment]
> 
> 
> @DenJohX Postscreen is a useful feature when the right ip's are whitelisted. However by default, providers use too many different outgoing ips, and too many other ips are blacklisted. What I did to "solve" this issue was to leave postscreen enabled and comment out `dnsbl.sorbs.net` within the `/etc/postfix/main.cf`. Magically the mail providers such as Gmail began working again via their rando choices from ip pool(s) without [significant/any] delay.
> 
> Although postscreen is cool, `dnsbl.sorbs.net` seems way too unbiased/monolithic and blocks Gmail ips. Apparently Google and Sorbs have been back and forth bickering for years to no resolve. Yes Gmail is home to large amounts of spam, but it's also home to massive amounts of legit users/mail. In my case, like yours, there are only 5 domains and I was able to run a tiny modoboa srv on a $5 768mb Vultr instance (~350mb used) by using Gmail as the webmail+antivirus and disabling clamav. Nothing nefarious about that, but sorbs thinks otherwise. Postscreen still blocks tons of other attempts using the other 4 major blacklists (or any others you add).
> 
> Also, there is this cron util: https://github.com/stevejenkins/postwhite which will find Gmail and other ranges based on SPF records and apply them to the postscreen whitelist. I haven't had a need to use that yet, but it's a workaround option if you want both postscreen and sorbs enabled. Hope that clarifies.

This solution worked just fine for me :)
